### ISSUE TITLE
Support: 🎬 Livestream Configuration Checklist

### ISSUE THREAD

**Issue by paulhchoi** [metrophilly/docs.metrophilly.org#163]
**This is to ensure all livestream configurations are ready before Sunday Worship.**

**Due: By Saturday 6 PM**

---

### Guide for working on this task:

- [Livestream Configuration Walkthrough](https://docs.google.com/document/d/1a4TKKc_wzeZQpRmYtNluZuHA99PP38EJtcRtW_ildsg/edit?usp=sharing)

### Needed Links (open 'em all!):

- [Restream.io dashboard](https://app.restream.io/channel)
- [Sanity.io Studio dashboard](https://metrochurch.sanity.studio/desk/)

### Checklist

- [ ] Update and confirm "Livestream Event" data in Sanity Studio is correct
- [ ] Update Restream's "Social Alerts" content
- [ ] When complete, shift card to "Ready to Review" and tag @dhy6785

**Comment by jessxu12** [comment]
@dhy6785 final bulletins up and deploying now, @paulhchoi said he would fix the other stuff for 4pm service

**Comment by paulhchoi** [comment]
deploying the changes now, should be pushed live in a few minutes — @dhy6785 mind reviewing again once it is? the homepage popover and the /sunday/ resource cards should be extent of it, but feel free to check out other parts of the site you think i may have missed

**Comment by dhy6785** [comment]
@paulhchoi @jessxu12 i think everything looks good
