### ISSUE TITLE
Support: 🎬 Livestream Configuration Checklist

### ISSUE THREAD

**Issue by paulhchoi** [metrophilly/docs.metrophilly.org#38]
**This is to ensure all livestream configurations are ready before Sunday Worship.**

**Due: By Saturday 6 PM**

---

### Guide for working on this task:

- [Livestream Configuration Walkthrough](https://docs.google.com/document/d/1a4TKKc_wzeZQpRmYtNluZuHA99PP38EJtcRtW_ildsg/edit?usp=sharing)

### Needed Links (open 'em all!):

- [Restream.io dashboard](https://app.restream.io/channel)
- [Sanity.io Studio dashboard](https://metrochurch.sanity.studio/desk/)

### Checklist

- [x] Update and confirm "Livestream Event" data in Sanity Studio is correct
- [x] Update Restream's "Social Alerts" content
- [x] When complete, shift card to "Ready to Review" and tag @$SUPPORT_REVIEWER

**Comment by ilgyo87** [comment]
ready for review @jessxu12

**Comment by paulhchoi** [comment]
@jessxu12 good note, yea that's probably a good idea going forward — looks like the drafts were the finals this week tho!

**Comment by jessxu12** [comment]
@paulhchoi hm yeah, we didn't get finals the past 2 weeks so it kinda worked out
